// <auto-generated />
using System;
using FitFox.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FitFox.Data.Migrations
{
    [DbContext(typeof(FitFoxDbContext))]
    [Migration("20250927123159_AddLessons")]
    partial class AddLessons
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FitFox.Data.Models.Achievement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasComment("The Identifier of the achievement.");

                    b.Property<int>("ConditionType")
                        .HasColumnType("int")
                        .HasComment("The condition for this achievement - LessonsLearned, MapsCovered, DailyQuestsCompleted, etc.");

                    b.Property<int>("ConditionValue")
                        .HasColumnType("int")
                        .HasComment("The value needed to get this achievement.");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasComment("What has been achieved in order to get this achievement.");

                    b.Property<string>("IconUrl")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)")
                        .HasComment("The Url to the achievement's icon.");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("The title of the achievement.");

                    b.HasKey("Id");

                    b.ToTable("Achievements");
                });

            modelBuilder.Entity("FitFox.Data.Models.Answer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasComment("The identifier of the answer.");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid>("QuestionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasComment("The answer content.");

                    b.HasKey("Id");

                    b.HasIndex("QuestionId");

                    b.ToTable("Answers");

                    b.HasData(
                        new
                        {
                            Id = new Guid("995bd8c0-98e5-441b-96f2-046c4e732022"),
                            IsDeleted = false,
                            QuestionId = new Guid("65e73cd9-dec1-4e46-8342-69b204c6b226"),
                            Text = "Protein, Fats, Carbohydrates"
                        },
                        new
                        {
                            Id = new Guid("6f682b25-0953-45bc-b4aa-3f77c44f0abd"),
                            IsDeleted = false,
                            QuestionId = new Guid("65e73cd9-dec1-4e46-8342-69b204c6b226"),
                            Text = "Fiber, Antioxidants, Enzymes"
                        },
                        new
                        {
                            Id = new Guid("754eb19b-0e7b-4f1f-aa8b-214b0c9e4ca1"),
                            IsDeleted = false,
                            QuestionId = new Guid("65e73cd9-dec1-4e46-8342-69b204c6b226"),
                            Text = "Vitamin C, Vitamin D, Vitamin E"
                        },
                        new
                        {
                            Id = new Guid("5635556a-dc6d-4a95-a804-a353787f29ac"),
                            IsDeleted = false,
                            QuestionId = new Guid("a8d6e1f2-5c33-4a0b-8cde-7e2f1a9b3d45"),
                            Text = "Protein"
                        },
                        new
                        {
                            Id = new Guid("ad15d6de-bc27-4f9c-925f-6efe5023521b"),
                            IsDeleted = false,
                            QuestionId = new Guid("a8d6e1f2-5c33-4a0b-8cde-7e2f1a9b3d45"),
                            Text = "Fats"
                        },
                        new
                        {
                            Id = new Guid("5f018738-98c2-45c8-91a8-4048ec7550ea"),
                            IsDeleted = false,
                            QuestionId = new Guid("a8d6e1f2-5c33-4a0b-8cde-7e2f1a9b3d45"),
                            Text = "Carbohydrates"
                        },
                        new
                        {
                            Id = new Guid("076d322b-61a0-4617-b7c7-adcfcd0e4a64"),
                            IsDeleted = false,
                            QuestionId = new Guid("c1f2b3e4-7d8a-4e5b-b2c3-9f0a1d2e3b56"),
                            Text = "Protein"
                        },
                        new
                        {
                            Id = new Guid("fc67a38b-6748-4df0-bdec-64ae01dce087"),
                            IsDeleted = false,
                            QuestionId = new Guid("c1f2b3e4-7d8a-4e5b-b2c3-9f0a1d2e3b56"),
                            Text = "Fats"
                        },
                        new
                        {
                            Id = new Guid("971018fd-870c-4834-b53e-9db728272f58"),
                            IsDeleted = false,
                            QuestionId = new Guid("c1f2b3e4-7d8a-4e5b-b2c3-9f0a1d2e3b56"),
                            Text = "Carbohydrates"
                        },
                        new
                        {
                            Id = new Guid("cd72868e-1d3c-40e2-99d2-9be1c6482f07"),
                            IsDeleted = false,
                            QuestionId = new Guid("d4e5f6a7-8b9c-4d0e-9f1a-2b3c4d5e6f78"),
                            Text = "Protein"
                        },
                        new
                        {
                            Id = new Guid("b052eb19-2983-4845-9e63-9cb44b67c5f1"),
                            IsDeleted = false,
                            QuestionId = new Guid("d4e5f6a7-8b9c-4d0e-9f1a-2b3c4d5e6f78"),
                            Text = "Fats"
                        },
                        new
                        {
                            Id = new Guid("b975ac50-9a54-4c2e-b36b-d57520da15b3"),
                            IsDeleted = false,
                            QuestionId = new Guid("d4e5f6a7-8b9c-4d0e-9f1a-2b3c4d5e6f78"),
                            Text = "Carbohydrates"
                        },
                        new
                        {
                            Id = new Guid("0b5e5a13-fa78-4329-9e1e-704b4e34c50a"),
                            IsDeleted = false,
                            QuestionId = new Guid("83fc33fc-0db2-4695-a950-c494eb58a73c"),
                            Text = "6"
                        },
                        new
                        {
                            Id = new Guid("84aa5695-c7af-4620-bb4e-fa860502744e"),
                            IsDeleted = false,
                            QuestionId = new Guid("83fc33fc-0db2-4695-a950-c494eb58a73c"),
                            Text = "4"
                        },
                        new
                        {
                            Id = new Guid("5b2e033a-3b69-42df-9b10-ac04fefbc4bd"),
                            IsDeleted = false,
                            QuestionId = new Guid("83fc33fc-0db2-4695-a950-c494eb58a73c"),
                            Text = "9"
                        },
                        new
                        {
                            Id = new Guid("bc272712-432e-4429-bbc0-c489ff3f0380"),
                            IsDeleted = false,
                            QuestionId = new Guid("e58fca52-c2da-44a4-b62f-9bd9bd7bb583"),
                            Text = "5"
                        },
                        new
                        {
                            Id = new Guid("e00f1bae-9e02-4afb-871f-23a1a3a9884f"),
                            IsDeleted = false,
                            QuestionId = new Guid("e58fca52-c2da-44a4-b62f-9bd9bd7bb583"),
                            Text = "4"
                        },
                        new
                        {
                            Id = new Guid("8a153745-ee3c-4fcb-b4cb-e73590bd90e3"),
                            IsDeleted = false,
                            QuestionId = new Guid("e58fca52-c2da-44a4-b62f-9bd9bd7bb583"),
                            Text = "9"
                        },
                        new
                        {
                            Id = new Guid("995c9a90-88fe-4fd2-8762-e3d46c2ea813"),
                            IsDeleted = false,
                            QuestionId = new Guid("c46cf154-ee4c-4c5d-ac35-4b4cf69639ce"),
                            Text = "2"
                        },
                        new
                        {
                            Id = new Guid("fe9167a4-2f11-4875-899d-83c9d4b031b7"),
                            IsDeleted = false,
                            QuestionId = new Guid("c46cf154-ee4c-4c5d-ac35-4b4cf69639ce"),
                            Text = "4"
                        },
                        new
                        {
                            Id = new Guid("a2845dd5-e2c0-4c39-87dd-255e08156b89"),
                            IsDeleted = false,
                            QuestionId = new Guid("c46cf154-ee4c-4c5d-ac35-4b4cf69639ce"),
                            Text = "9"
                        });
                });

            modelBuilder.Entity("FitFox.Data.Models.ApplicationUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CurrentXP")
                        .HasColumnType("int")
                        .HasComment("The current XP of the user. Overall XP, not of the current level.");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid>("LevelId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Identifier of the level.");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("LevelId");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("FitFox.Data.Models.Lesson", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasComment("The identifier of the lesson.");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid>("MapId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("The identifier of the map that this lesson belongs to.");

                    b.Property<int>("OrderNumber")
                        .HasColumnType("int")
                        .HasComment("The order of this lesson in the map.");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasComment("The tile of the lesson.");

                    b.Property<int>("XP")
                        .HasColumnType("int")
                        .HasComment("The amount of XP this lesson grants the user on completion.");

                    b.HasKey("Id");

                    b.HasIndex("MapId");

                    b.ToTable("Lessons");

                    b.HasData(
                        new
                        {
                            Id = new Guid("26a98b9c-2a98-4714-8d28-99f6ed419834"),
                            IsDeleted = false,
                            MapId = new Guid("04493112-8b84-43be-b926-5a32c5524ac2"),
                            OrderNumber = 1,
                            Title = "Macronutrients",
                            XP = 100
                        },
                        new
                        {
                            Id = new Guid("97300d33-6cc5-48ba-b495-ff21d5b16419"),
                            IsDeleted = false,
                            MapId = new Guid("04493112-8b84-43be-b926-5a32c5524ac2"),
                            OrderNumber = 2,
                            Title = "Macronutrient Ratios",
                            XP = 100
                        },
                        new
                        {
                            Id = new Guid("98479667-cd5b-4953-a442-de348acda994"),
                            IsDeleted = false,
                            MapId = new Guid("04493112-8b84-43be-b926-5a32c5524ac2"),
                            OrderNumber = 5,
                            Title = "Hydration and Electrolytes",
                            XP = 100
                        },
                        new
                        {
                            Id = new Guid("77c74f8c-a3ef-4cb8-8a2c-b71ca6ecd33e"),
                            IsDeleted = false,
                            MapId = new Guid("04493112-8b84-43be-b926-5a32c5524ac2"),
                            OrderNumber = 3,
                            Title = "Protein Quality and Timing",
                            XP = 100
                        },
                        new
                        {
                            Id = new Guid("0491fb6d-5264-4beb-88e6-a247489c4825"),
                            IsDeleted = false,
                            MapId = new Guid("04493112-8b84-43be-b926-5a32c5524ac2"),
                            OrderNumber = 4,
                            Title = "Micronutrients",
                            XP = 100
                        },
                        new
                        {
                            Id = new Guid("b1adc18d-8c55-4a74-8bf6-a9a2943fd9e7"),
                            IsDeleted = false,
                            MapId = new Guid("1afe12ea-606d-49d0-adb9-5f8311d86618"),
                            OrderNumber = 1,
                            Title = "Benefits of Resistance Training",
                            XP = 100
                        },
                        new
                        {
                            Id = new Guid("cde73646-a8fb-4131-9308-8269ea662c54"),
                            IsDeleted = false,
                            MapId = new Guid("1afe12ea-606d-49d0-adb9-5f8311d86618"),
                            OrderNumber = 2,
                            Title = "Exercises and Muscles Targeted",
                            XP = 100
                        },
                        new
                        {
                            Id = new Guid("8e10a739-c7a9-4c9e-887c-b2599be94f3a"),
                            IsDeleted = false,
                            MapId = new Guid("1afe12ea-606d-49d0-adb9-5f8311d86618"),
                            OrderNumber = 3,
                            Title = "Training Splits and Frequency",
                            XP = 100
                        },
                        new
                        {
                            Id = new Guid("81476c31-4e91-41d5-b37e-422e97b5882e"),
                            IsDeleted = false,
                            MapId = new Guid("1afe12ea-606d-49d0-adb9-5f8311d86618"),
                            OrderNumber = 4,
                            Title = "Compound vs Isolation Movements",
                            XP = 100
                        },
                        new
                        {
                            Id = new Guid("7e065ddc-a469-4bbe-b205-113c3d96f4c5"),
                            IsDeleted = false,
                            MapId = new Guid("1afe12ea-606d-49d0-adb9-5f8311d86618"),
                            OrderNumber = 5,
                            Title = "Recovery and Rest",
                            XP = 100
                        });
                });

            modelBuilder.Entity("FitFox.Data.Models.Level", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasComment("The identifier of the level.");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("LevelNumber")
                        .HasColumnType("int")
                        .HasComment("The number representing the level. Incrementing by 1.");

                    b.Property<string>("LevelTitle")
                        .HasColumnType("nvarchar(max)")
                        .HasComment("The title granted for the level. Every 10 levels the user gets title of the level.");

                    b.Property<int>("RequiredXP")
                        .HasColumnType("int")
                        .HasComment("The XP that is required to get to this level.");

                    b.HasKey("Id");

                    b.ToTable("Levels");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            IsDeleted = false,
                            LevelNumber = 1,
                            LevelTitle = "Newbie",
                            RequiredXP = 0
                        });
                });

            modelBuilder.Entity("FitFox.Data.Models.Map", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasComment("The identifier of the map.");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasComment("The description of the map.");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("MapCategory")
                        .HasColumnType("int")
                        .HasComment("The category of the map - training, nutrition, hydration, recovery, etc.");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasComment("The display name of the map.");

                    b.HasKey("Id");

                    b.ToTable("Maps");

                    b.HasData(
                        new
                        {
                            Id = new Guid("1afe12ea-606d-49d0-adb9-5f8311d86618"),
                            Description = "The basics of training with weights.",
                            IsDeleted = false,
                            MapCategory = 0,
                            Title = "Training"
                        },
                        new
                        {
                            Id = new Guid("04493112-8b84-43be-b926-5a32c5524ac2"),
                            Description = "The basics of nutrition focused on gym progression.",
                            IsDeleted = false,
                            MapCategory = 1,
                            Title = "Nutrition"
                        });
                });

            modelBuilder.Entity("FitFox.Data.Models.MappingModels.UserAchievement", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AchievementId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("EarnedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("UserId", "AchievementId");

                    b.HasIndex("AchievementId");

                    b.ToTable("UsersAchievements");
                });

            modelBuilder.Entity("FitFox.Data.Models.MappingModels.UserLesson", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("LessonId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId", "LessonId");

                    b.HasIndex("LessonId");

                    b.ToTable("UsersLessons");
                });

            modelBuilder.Entity("FitFox.Data.Models.MappingModels.UserMap", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("MapId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId", "MapId");

                    b.HasIndex("MapId");

                    b.ToTable("UsersMaps");
                });

            modelBuilder.Entity("FitFox.Data.Models.Question", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Identifier of the question.");

                    b.Property<Guid?>("CorrectAnswerId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("The identifier of the correct answer.");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid>("LessonId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Identifier of the lesson that this question belongs to.");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasComment("The question content.");

                    b.HasKey("Id");

                    b.HasIndex("CorrectAnswerId");

                    b.HasIndex("LessonId");

                    b.ToTable("Questions");

                    b.HasData(
                        new
                        {
                            Id = new Guid("65e73cd9-dec1-4e46-8342-69b204c6b226"),
                            CorrectAnswerId = new Guid("995bd8c0-98e5-441b-96f2-046c4e732022"),
                            IsDeleted = false,
                            LessonId = new Guid("26a98b9c-2a98-4714-8d28-99f6ed419834"),
                            Text = "Which are the 3 macronutrients?"
                        },
                        new
                        {
                            Id = new Guid("a8d6e1f2-5c33-4a0b-8cde-7e2f1a9b3d45"),
                            CorrectAnswerId = new Guid("ad15d6de-bc27-4f9c-925f-6efe5023521b"),
                            IsDeleted = false,
                            LessonId = new Guid("26a98b9c-2a98-4714-8d28-99f6ed419834"),
                            Text = "Which macronutrient regulates hormone production?"
                        },
                        new
                        {
                            Id = new Guid("c1f2b3e4-7d8a-4e5b-b2c3-9f0a1d2e3b56"),
                            CorrectAnswerId = new Guid("971018fd-870c-4834-b53e-9db728272f58"),
                            IsDeleted = false,
                            LessonId = new Guid("26a98b9c-2a98-4714-8d28-99f6ed419834"),
                            Text = "Which macronutrient is the main source of energy for the body?"
                        },
                        new
                        {
                            Id = new Guid("d4e5f6a7-8b9c-4d0e-9f1a-2b3c4d5e6f78"),
                            CorrectAnswerId = new Guid("cd72868e-1d3c-40e2-99d2-9be1c6482f07"),
                            IsDeleted = false,
                            LessonId = new Guid("26a98b9c-2a98-4714-8d28-99f6ed419834"),
                            Text = "Which nutrient is primarily used for muscle repair?"
                        },
                        new
                        {
                            Id = new Guid("83fc33fc-0db2-4695-a950-c494eb58a73c"),
                            CorrectAnswerId = new Guid("5b2e033a-3b69-42df-9b10-ac04fefbc4bd"),
                            IsDeleted = false,
                            LessonId = new Guid("26a98b9c-2a98-4714-8d28-99f6ed419834"),
                            Text = "How many calories does 1 gram of fat contain?"
                        },
                        new
                        {
                            Id = new Guid("e58fca52-c2da-44a4-b62f-9bd9bd7bb583"),
                            CorrectAnswerId = new Guid("e00f1bae-9e02-4afb-871f-23a1a3a9884f"),
                            IsDeleted = false,
                            LessonId = new Guid("26a98b9c-2a98-4714-8d28-99f6ed419834"),
                            Text = "How many calories does 1 gram of carbohydrates contain?"
                        },
                        new
                        {
                            Id = new Guid("c46cf154-ee4c-4c5d-ac35-4b4cf69639ce"),
                            CorrectAnswerId = new Guid("fe9167a4-2f11-4875-899d-83c9d4b031b7"),
                            IsDeleted = false,
                            LessonId = new Guid("26a98b9c-2a98-4714-8d28-99f6ed419834"),
                            Text = "How many calories does 1 gram of protein contain?"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("FitFox.Data.Models.Answer", b =>
                {
                    b.HasOne("FitFox.Data.Models.Question", "Question")
                        .WithMany("AnswerOptions")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Question");
                });

            modelBuilder.Entity("FitFox.Data.Models.ApplicationUser", b =>
                {
                    b.HasOne("FitFox.Data.Models.Level", "Level")
                        .WithMany("Users")
                        .HasForeignKey("LevelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Level");
                });

            modelBuilder.Entity("FitFox.Data.Models.Lesson", b =>
                {
                    b.HasOne("FitFox.Data.Models.Map", "Map")
                        .WithMany("Lessons")
                        .HasForeignKey("MapId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Map");
                });

            modelBuilder.Entity("FitFox.Data.Models.MappingModels.UserAchievement", b =>
                {
                    b.HasOne("FitFox.Data.Models.Achievement", "Achievement")
                        .WithMany("AchievementUsers")
                        .HasForeignKey("AchievementId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FitFox.Data.Models.ApplicationUser", "User")
                        .WithMany("UserAchievements")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Achievement");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FitFox.Data.Models.MappingModels.UserLesson", b =>
                {
                    b.HasOne("FitFox.Data.Models.Lesson", "Lesson")
                        .WithMany("LessonUsers")
                        .HasForeignKey("LessonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FitFox.Data.Models.ApplicationUser", "User")
                        .WithMany("UserLessons")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lesson");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FitFox.Data.Models.MappingModels.UserMap", b =>
                {
                    b.HasOne("FitFox.Data.Models.Map", "Map")
                        .WithMany("MapUsers")
                        .HasForeignKey("MapId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FitFox.Data.Models.ApplicationUser", "User")
                        .WithMany("UserMaps")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Map");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FitFox.Data.Models.Question", b =>
                {
                    b.HasOne("FitFox.Data.Models.Answer", "CorrectAnswer")
                        .WithMany()
                        .HasForeignKey("CorrectAnswerId");

                    b.HasOne("FitFox.Data.Models.Lesson", "Lesson")
                        .WithMany("Questions")
                        .HasForeignKey("LessonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CorrectAnswer");

                    b.Navigation("Lesson");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("FitFox.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("FitFox.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FitFox.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("FitFox.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FitFox.Data.Models.Achievement", b =>
                {
                    b.Navigation("AchievementUsers");
                });

            modelBuilder.Entity("FitFox.Data.Models.ApplicationUser", b =>
                {
                    b.Navigation("UserAchievements");

                    b.Navigation("UserLessons");

                    b.Navigation("UserMaps");
                });

            modelBuilder.Entity("FitFox.Data.Models.Lesson", b =>
                {
                    b.Navigation("LessonUsers");

                    b.Navigation("Questions");
                });

            modelBuilder.Entity("FitFox.Data.Models.Level", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("FitFox.Data.Models.Map", b =>
                {
                    b.Navigation("Lessons");

                    b.Navigation("MapUsers");
                });

            modelBuilder.Entity("FitFox.Data.Models.Question", b =>
                {
                    b.Navigation("AnswerOptions");
                });
#pragma warning restore 612, 618
        }
    }
}
