// <auto-generated />
using System;
using FitFox.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FitFox.Data.Migrations
{
    [DbContext(typeof(FitFoxDbContext))]
    [Migration("20250928102724_SeedAnswersForQuestionsFromLessonFour")]
    partial class SeedAnswersForQuestionsFromLessonFour
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FitFox.Data.Models.Achievement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasComment("The Identifier of the achievement.");

                    b.Property<int>("ConditionType")
                        .HasColumnType("int")
                        .HasComment("The condition for this achievement - LessonsLearned, MapsCovered, DailyQuestsCompleted, etc.");

                    b.Property<int>("ConditionValue")
                        .HasColumnType("int")
                        .HasComment("The value needed to get this achievement.");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasComment("What has been achieved in order to get this achievement.");

                    b.Property<string>("IconUrl")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)")
                        .HasComment("The Url to the achievement's icon.");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("The title of the achievement.");

                    b.HasKey("Id");

                    b.ToTable("Achievements");
                });

            modelBuilder.Entity("FitFox.Data.Models.Answer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasComment("The identifier of the answer.");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid>("QuestionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasComment("The answer content.");

                    b.HasKey("Id");

                    b.HasIndex("QuestionId");

                    b.ToTable("Answers");

                    b.HasData(
                        new
                        {
                            Id = new Guid("995bd8c0-98e5-441b-96f2-046c4e732022"),
                            IsDeleted = false,
                            QuestionId = new Guid("65e73cd9-dec1-4e46-8342-69b204c6b226"),
                            Text = "Protein, Fats, Carbohydrates"
                        },
                        new
                        {
                            Id = new Guid("6f682b25-0953-45bc-b4aa-3f77c44f0abd"),
                            IsDeleted = false,
                            QuestionId = new Guid("65e73cd9-dec1-4e46-8342-69b204c6b226"),
                            Text = "Fiber, Antioxidants, Enzymes"
                        },
                        new
                        {
                            Id = new Guid("754eb19b-0e7b-4f1f-aa8b-214b0c9e4ca1"),
                            IsDeleted = false,
                            QuestionId = new Guid("65e73cd9-dec1-4e46-8342-69b204c6b226"),
                            Text = "Vitamin C, Vitamin D, Vitamin E"
                        },
                        new
                        {
                            Id = new Guid("5635556a-dc6d-4a95-a804-a353787f29ac"),
                            IsDeleted = false,
                            QuestionId = new Guid("a8d6e1f2-5c33-4a0b-8cde-7e2f1a9b3d45"),
                            Text = "Protein"
                        },
                        new
                        {
                            Id = new Guid("ad15d6de-bc27-4f9c-925f-6efe5023521b"),
                            IsDeleted = false,
                            QuestionId = new Guid("a8d6e1f2-5c33-4a0b-8cde-7e2f1a9b3d45"),
                            Text = "Fats"
                        },
                        new
                        {
                            Id = new Guid("5f018738-98c2-45c8-91a8-4048ec7550ea"),
                            IsDeleted = false,
                            QuestionId = new Guid("a8d6e1f2-5c33-4a0b-8cde-7e2f1a9b3d45"),
                            Text = "Carbohydrates"
                        },
                        new
                        {
                            Id = new Guid("076d322b-61a0-4617-b7c7-adcfcd0e4a64"),
                            IsDeleted = false,
                            QuestionId = new Guid("c1f2b3e4-7d8a-4e5b-b2c3-9f0a1d2e3b56"),
                            Text = "Protein"
                        },
                        new
                        {
                            Id = new Guid("fc67a38b-6748-4df0-bdec-64ae01dce087"),
                            IsDeleted = false,
                            QuestionId = new Guid("c1f2b3e4-7d8a-4e5b-b2c3-9f0a1d2e3b56"),
                            Text = "Fats"
                        },
                        new
                        {
                            Id = new Guid("971018fd-870c-4834-b53e-9db728272f58"),
                            IsDeleted = false,
                            QuestionId = new Guid("c1f2b3e4-7d8a-4e5b-b2c3-9f0a1d2e3b56"),
                            Text = "Carbohydrates"
                        },
                        new
                        {
                            Id = new Guid("cd72868e-1d3c-40e2-99d2-9be1c6482f07"),
                            IsDeleted = false,
                            QuestionId = new Guid("d4e5f6a7-8b9c-4d0e-9f1a-2b3c4d5e6f78"),
                            Text = "Protein"
                        },
                        new
                        {
                            Id = new Guid("b052eb19-2983-4845-9e63-9cb44b67c5f1"),
                            IsDeleted = false,
                            QuestionId = new Guid("d4e5f6a7-8b9c-4d0e-9f1a-2b3c4d5e6f78"),
                            Text = "Fats"
                        },
                        new
                        {
                            Id = new Guid("b975ac50-9a54-4c2e-b36b-d57520da15b3"),
                            IsDeleted = false,
                            QuestionId = new Guid("d4e5f6a7-8b9c-4d0e-9f1a-2b3c4d5e6f78"),
                            Text = "Carbohydrates"
                        },
                        new
                        {
                            Id = new Guid("0b5e5a13-fa78-4329-9e1e-704b4e34c50a"),
                            IsDeleted = false,
                            QuestionId = new Guid("83fc33fc-0db2-4695-a950-c494eb58a73c"),
                            Text = "6"
                        },
                        new
                        {
                            Id = new Guid("84aa5695-c7af-4620-bb4e-fa860502744e"),
                            IsDeleted = false,
                            QuestionId = new Guid("83fc33fc-0db2-4695-a950-c494eb58a73c"),
                            Text = "4"
                        },
                        new
                        {
                            Id = new Guid("5b2e033a-3b69-42df-9b10-ac04fefbc4bd"),
                            IsDeleted = false,
                            QuestionId = new Guid("83fc33fc-0db2-4695-a950-c494eb58a73c"),
                            Text = "9"
                        },
                        new
                        {
                            Id = new Guid("bc272712-432e-4429-bbc0-c489ff3f0380"),
                            IsDeleted = false,
                            QuestionId = new Guid("e58fca52-c2da-44a4-b62f-9bd9bd7bb583"),
                            Text = "5"
                        },
                        new
                        {
                            Id = new Guid("e00f1bae-9e02-4afb-871f-23a1a3a9884f"),
                            IsDeleted = false,
                            QuestionId = new Guid("e58fca52-c2da-44a4-b62f-9bd9bd7bb583"),
                            Text = "4"
                        },
                        new
                        {
                            Id = new Guid("8a153745-ee3c-4fcb-b4cb-e73590bd90e3"),
                            IsDeleted = false,
                            QuestionId = new Guid("e58fca52-c2da-44a4-b62f-9bd9bd7bb583"),
                            Text = "9"
                        },
                        new
                        {
                            Id = new Guid("995c9a90-88fe-4fd2-8762-e3d46c2ea813"),
                            IsDeleted = false,
                            QuestionId = new Guid("c46cf154-ee4c-4c5d-ac35-4b4cf69639ce"),
                            Text = "2"
                        },
                        new
                        {
                            Id = new Guid("fe9167a4-2f11-4875-899d-83c9d4b031b7"),
                            IsDeleted = false,
                            QuestionId = new Guid("c46cf154-ee4c-4c5d-ac35-4b4cf69639ce"),
                            Text = "4"
                        },
                        new
                        {
                            Id = new Guid("a2845dd5-e2c0-4c39-87dd-255e08156b89"),
                            IsDeleted = false,
                            QuestionId = new Guid("c46cf154-ee4c-4c5d-ac35-4b4cf69639ce"),
                            Text = "9"
                        },
                        new
                        {
                            Id = new Guid("3c3fd6c5-5c2d-4ef4-b2a3-fdf7f4d7dc94"),
                            IsDeleted = false,
                            QuestionId = new Guid("725ac1b4-5362-484a-964a-4a1bc95a2aab"),
                            Text = "1.7–2.5 grams"
                        },
                        new
                        {
                            Id = new Guid("f52e1b3e-4f48-4d48-9880-3ecfcf4cc91f"),
                            IsDeleted = false,
                            QuestionId = new Guid("725ac1b4-5362-484a-964a-4a1bc95a2aab"),
                            Text = "0.5 grams"
                        },
                        new
                        {
                            Id = new Guid("04ff28e3-1c76-43fb-9f2e-50dc89d4574d"),
                            IsDeleted = false,
                            QuestionId = new Guid("725ac1b4-5362-484a-964a-4a1bc95a2aab"),
                            Text = "5 grams"
                        },
                        new
                        {
                            Id = new Guid("0f9d15b7-8b2f-4df7-8613-93d80d3d3c34"),
                            IsDeleted = false,
                            QuestionId = new Guid("ab0fda0c-dca4-4b12-a690-8e1b311ee5de"),
                            Text = "Carbohydrates"
                        },
                        new
                        {
                            Id = new Guid("c145af32-bb34-4c58-8f6a-63b59ad2e497"),
                            IsDeleted = false,
                            QuestionId = new Guid("ab0fda0c-dca4-4b12-a690-8e1b311ee5de"),
                            Text = "Proteins"
                        },
                        new
                        {
                            Id = new Guid("8f960e0f-3f31-4f12-abe7-8e055fba26b0"),
                            IsDeleted = false,
                            QuestionId = new Guid("ab0fda0c-dca4-4b12-a690-8e1b311ee5de"),
                            Text = "Fats"
                        },
                        new
                        {
                            Id = new Guid("6c44c89a-c257-4cd5-8653-c3f523b42f15"),
                            IsDeleted = false,
                            QuestionId = new Guid("c3dc5b10-c49e-4c55-82bf-19588f1ce0a4"),
                            Text = "Proteins"
                        },
                        new
                        {
                            Id = new Guid("3a5ef8a4-68ae-464a-8e93-7c4d8b1f1a5a"),
                            IsDeleted = false,
                            QuestionId = new Guid("c3dc5b10-c49e-4c55-82bf-19588f1ce0a4"),
                            Text = "Carbohydrates"
                        },
                        new
                        {
                            Id = new Guid("ac0270a6-9dc2-4c4c-9e40-16ac51137b34"),
                            IsDeleted = false,
                            QuestionId = new Guid("c3dc5b10-c49e-4c55-82bf-19588f1ce0a4"),
                            Text = "Fats"
                        },
                        new
                        {
                            Id = new Guid("f3c7b58d-8fbb-4d6e-b2f5-3e6f2d9a7b21"),
                            IsDeleted = false,
                            QuestionId = new Guid("b4baf54c-59b6-4b9d-91d9-7e3352b5d3ee"),
                            Text = "Fats"
                        },
                        new
                        {
                            Id = new Guid("d1f64c0a-7d32-466b-94ae-2b0a1f7d1f3f"),
                            IsDeleted = false,
                            QuestionId = new Guid("b4baf54c-59b6-4b9d-91d9-7e3352b5d3ee"),
                            Text = "Proteins"
                        },
                        new
                        {
                            Id = new Guid("aa5d6f8b-2d44-4f0e-bd35-5e1c9d4b2f9e"),
                            IsDeleted = false,
                            QuestionId = new Guid("b4baf54c-59b6-4b9d-91d9-7e3352b5d3ee"),
                            Text = "Carbohydrates"
                        },
                        new
                        {
                            Id = new Guid("a8e4f0c5-5a2c-4e2e-98d1-0f7bfa36c1b7"),
                            IsDeleted = false,
                            QuestionId = new Guid("c29ae0bc-eb61-45c1-be09-2e24ca66862b"),
                            Text = "Transport nutrients and waste, as well as regulate body temperature"
                        },
                        new
                        {
                            Id = new Guid("f2c3a97e-1b34-4a36-8f48-2f3c1d0d5a5b"),
                            IsDeleted = false,
                            QuestionId = new Guid("c29ae0bc-eb61-45c1-be09-2e24ca66862b"),
                            Text = "Store energy"
                        },
                        new
                        {
                            Id = new Guid("b1d3e972-3f27-49f3-9e5b-5f2a8c4a2b89"),
                            IsDeleted = false,
                            QuestionId = new Guid("c29ae0bc-eb61-45c1-be09-2e24ca66862b"),
                            Text = "Produce hormones"
                        },
                        new
                        {
                            Id = new Guid("d0c6a5e2-3c2b-4f85-8ed2-1a9b6c7d4f2a"),
                            IsDeleted = false,
                            QuestionId = new Guid("d76f8572-c76d-4ea6-96e2-88f94b2ef5db"),
                            Text = "Sodium"
                        },
                        new
                        {
                            Id = new Guid("e9a3d7b1-7c18-4f5e-9b3d-2c1f4a9e6d8b"),
                            IsDeleted = false,
                            QuestionId = new Guid("d76f8572-c76d-4ea6-96e2-88f94b2ef5db"),
                            Text = "Potassium"
                        },
                        new
                        {
                            Id = new Guid("fa1c3b47-5e6a-4c8d-9e2b-0d9c2a4e7b1f"),
                            IsDeleted = false,
                            QuestionId = new Guid("d76f8572-c76d-4ea6-96e2-88f94b2ef5db"),
                            Text = "Magnesium"
                        },
                        new
                        {
                            Id = new Guid("b8f7d3c4-1a5b-4e8c-9d2a-0f4e3c7b2d1a"),
                            IsDeleted = false,
                            QuestionId = new Guid("5ef2fcf6-df7a-4f3d-9958-3d3c20fe9b90"),
                            Text = "Potassium"
                        },
                        new
                        {
                            Id = new Guid("c7e2f8b1-4d5a-4c9e-8b1c-3f2e6a4d1b2f"),
                            IsDeleted = false,
                            QuestionId = new Guid("5ef2fcf6-df7a-4f3d-9958-3d3c20fe9b90"),
                            Text = "Sodium"
                        },
                        new
                        {
                            Id = new Guid("d3f1b2a5-5e6c-4d9f-9c1a-2e3f4a5b6c7d"),
                            IsDeleted = false,
                            QuestionId = new Guid("5ef2fcf6-df7a-4f3d-9958-3d3c20fe9b90"),
                            Text = "Chloride"
                        },
                        new
                        {
                            Id = new Guid("c3d2e1f0-4b5a-4c8d-9e2f-1a3b4c5d6e7f"),
                            IsDeleted = false,
                            QuestionId = new Guid("4c550c86-a27f-480d-8a34-26a5d94d7bb3"),
                            Text = "Excessive energy"
                        },
                        new
                        {
                            Id = new Guid("f1b2d3a4-5e6c-4f8d-9a1b-2c3d4e5f6a7b"),
                            IsDeleted = false,
                            QuestionId = new Guid("4c550c86-a27f-480d-8a34-26a5d94d7bb3"),
                            Text = "Dark colored urine"
                        },
                        new
                        {
                            Id = new Guid("d4e3f2a1-5b6c-4d8f-9a2b-3c4d5e6f7a8b"),
                            IsDeleted = false,
                            QuestionId = new Guid("4c550c86-a27f-480d-8a34-26a5d94d7bb3"),
                            Text = "High blood sugar"
                        },
                        new
                        {
                            Id = new Guid("c7b6a5d4-8e9f-4f0a-9b2c-6d7e8f9a0b1d"),
                            IsDeleted = false,
                            QuestionId = new Guid("3b1a72e5-e73e-4e8d-833e-b92a61eb2664"),
                            Text = "5 liters"
                        },
                        new
                        {
                            Id = new Guid("d8c7b6a5-9f0a-4b1c-8d3e-7f8a9b0c1d2e"),
                            IsDeleted = false,
                            QuestionId = new Guid("3b1a72e5-e73e-4e8d-833e-b92a61eb2664"),
                            Text = "1 liter"
                        },
                        new
                        {
                            Id = new Guid("f6a5b4c3-7d8e-4f9a-8b1c-5d6e7f8a9b0c"),
                            IsDeleted = false,
                            QuestionId = new Guid("3b1a72e5-e73e-4e8d-833e-b92a61eb2664"),
                            Text = "2–3 liters"
                        },
                        new
                        {
                            Id = new Guid("c1f0e9d8-2b3c-4d5e-8f6a-0c1d2e3f4a5b"),
                            IsDeleted = false,
                            QuestionId = new Guid("2cd2b95d-63c0-4c7f-9485-3df385a91476"),
                            Text = "Potassium"
                        },
                        new
                        {
                            Id = new Guid("f0e9d8c7-1b2c-4d3e-9f5a-9b0c1d2e3f4a"),
                            IsDeleted = false,
                            QuestionId = new Guid("2cd2b95d-63c0-4c7f-9485-3df385a91476"),
                            Text = "Sodium"
                        },
                        new
                        {
                            Id = new Guid("d2c1f0e9-3b4c-4d6e-9f7b-1d2e3f4a5b6c"),
                            IsDeleted = false,
                            QuestionId = new Guid("2cd2b95d-63c0-4c7f-9485-3df385a91476"),
                            Text = "Magnesium"
                        },
                        new
                        {
                            Id = new Guid("f4e3d2c1-5b6c-4d8e-9f9d-3f4a5b6c7d8e"),
                            IsDeleted = false,
                            QuestionId = new Guid("3bbce0fb-8e12-4a03-837d-9ac269f282ff"),
                            Text = "Muscle relaxation"
                        },
                        new
                        {
                            Id = new Guid("c5f4e3d2-6b7c-4d9f-8f0e-4a5b6c7d8e9f"),
                            IsDeleted = false,
                            QuestionId = new Guid("3bbce0fb-8e12-4a03-837d-9ac269f282ff"),
                            Text = "Improved sleep"
                        },
                        new
                        {
                            Id = new Guid("d6c5f4e3-7b8c-4daf-9f1a-5b6c7d8e9f0a"),
                            IsDeleted = false,
                            QuestionId = new Guid("3bbce0fb-8e12-4a03-837d-9ac269f282ff"),
                            Text = "Muscle and nerve function"
                        },
                        new
                        {
                            Id = new Guid("c3b1f8a4-2d7e-4b9c-9a1f-0b6d3e5f7a1b"),
                            IsDeleted = false,
                            QuestionId = new Guid("e74d6670-97b6-42c9-8464-881dbb6bfa9d"),
                            Text = "Eggs"
                        },
                        new
                        {
                            Id = new Guid("d1e5c2b3-3f8a-4c6d-8b9c-1d2e3f4a5b6c"),
                            IsDeleted = false,
                            QuestionId = new Guid("e74d6670-97b6-42c9-8464-881dbb6bfa9d"),
                            Text = "Rice"
                        },
                        new
                        {
                            Id = new Guid("f2a3b4c5-4d9e-4f8a-9b0c-2f3d4e5a6b7c"),
                            IsDeleted = false,
                            QuestionId = new Guid("e74d6670-97b6-42c9-8464-881dbb6bfa9d"),
                            Text = "Lentils"
                        },
                        new
                        {
                            Id = new Guid("c8d9e0f1-2b3c-4d5e-8f1a-4b6c7d8e9f0a"),
                            IsDeleted = false,
                            QuestionId = new Guid("b850b9da-babb-465e-96b4-99639f04711e"),
                            Text = "Before sleep"
                        },
                        new
                        {
                            Id = new Guid("b7c8d9e0-1a2b-4c3d-9f4e-3a5b6c7d8e9f"),
                            IsDeleted = false,
                            QuestionId = new Guid("b850b9da-babb-465e-96b4-99639f04711e"),
                            Text = "Immediately post-workout"
                        },
                        new
                        {
                            Id = new Guid("d9e0f1a2-3c4d-4e5f-9b2c-5c7d8e9f0a1b"),
                            IsDeleted = false,
                            QuestionId = new Guid("b850b9da-babb-465e-96b4-99639f04711e"),
                            Text = "Anytime during the day"
                        },
                        new
                        {
                            Id = new Guid("e0f1a2b3-4d5e-4f6a-8c3d-6d7e8f9a0b1c"),
                            IsDeleted = false,
                            QuestionId = new Guid("34c91eb1-1e3b-4f7b-bf02-8b9f34653023"),
                            Text = "Whey protein"
                        },
                        new
                        {
                            Id = new Guid("f1a2b3c4-5e6f-4d7a-9b4c-7e8f9a0b1c2d"),
                            IsDeleted = false,
                            QuestionId = new Guid("34c91eb1-1e3b-4f7b-bf02-8b9f34653023"),
                            Text = "Casein protein"
                        },
                        new
                        {
                            Id = new Guid("a2b3c4d5-6f7e-4d8a-8c5d-8f9a0b1c2d3e"),
                            IsDeleted = false,
                            QuestionId = new Guid("34c91eb1-1e3b-4f7b-bf02-8b9f34653023"),
                            Text = "Soy protein"
                        },
                        new
                        {
                            Id = new Guid("c4d5e6f7-8a9b-4d0c-8e7f-0b1c2d3e4f5a"),
                            IsDeleted = false,
                            QuestionId = new Guid("cb1eb27c-eb7a-49f1-bf83-5b89a8dca794"),
                            Text = "Immediately post-workout"
                        },
                        new
                        {
                            Id = new Guid("d5e6f7a8-9b0c-4d1d-9f8a-1c2d3e4f5a6b"),
                            IsDeleted = false,
                            QuestionId = new Guid("cb1eb27c-eb7a-49f1-bf83-5b89a8dca794"),
                            Text = "Before breakfast"
                        },
                        new
                        {
                            Id = new Guid("b3c4d5e6-7f8a-4d9b-9d6e-9a0b1c2d3e4f"),
                            IsDeleted = false,
                            QuestionId = new Guid("cb1eb27c-eb7a-49f1-bf83-5b89a8dca794"),
                            Text = "Before sleep"
                        },
                        new
                        {
                            Id = new Guid("f7a8b9c0-1d2e-4d3f-9b0c-3e4f5a6b7c8d"),
                            IsDeleted = false,
                            QuestionId = new Guid("ddbf95d6-d691-48e2-8c7d-6ce2150e3ac5"),
                            Text = "Reduce calorie intake"
                        },
                        new
                        {
                            Id = new Guid("a8b9c0d1-2e3f-4d4a-8c1d-4f5a6b7c8d9e"),
                            IsDeleted = false,
                            QuestionId = new Guid("ddbf95d6-d691-48e2-8c7d-6ce2150e3ac5"),
                            Text = "Increase fat intake"
                        },
                        new
                        {
                            Id = new Guid("e6f7a8b9-0c1d-4d2e-8a9b-2d3e4f5a6b7c"),
                            IsDeleted = false,
                            QuestionId = new Guid("ddbf95d6-d691-48e2-8c7d-6ce2150e3ac5"),
                            Text = "Provide all essential amino acids"
                        });
                });

            modelBuilder.Entity("FitFox.Data.Models.ApplicationUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CurrentXP")
                        .HasColumnType("int")
                        .HasComment("The current XP of the user. Overall XP, not of the current level.");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid>("LevelId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Identifier of the level.");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("LevelId");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("FitFox.Data.Models.Lesson", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasComment("The identifier of the lesson.");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid>("MapId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("The identifier of the map that this lesson belongs to.");

                    b.Property<int>("OrderNumber")
                        .HasColumnType("int")
                        .HasComment("The order of this lesson in the map.");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasComment("The tile of the lesson.");

                    b.Property<int>("XP")
                        .HasColumnType("int")
                        .HasComment("The amount of XP this lesson grants the user on completion.");

                    b.HasKey("Id");

                    b.HasIndex("MapId");

                    b.ToTable("Lessons");

                    b.HasData(
                        new
                        {
                            Id = new Guid("26a98b9c-2a98-4714-8d28-99f6ed419834"),
                            IsDeleted = false,
                            MapId = new Guid("04493112-8b84-43be-b926-5a32c5524ac2"),
                            OrderNumber = 1,
                            Title = "Macronutrients",
                            XP = 100
                        },
                        new
                        {
                            Id = new Guid("97300d33-6cc5-48ba-b495-ff21d5b16419"),
                            IsDeleted = false,
                            MapId = new Guid("04493112-8b84-43be-b926-5a32c5524ac2"),
                            OrderNumber = 2,
                            Title = "Macronutrient Ratios",
                            XP = 100
                        },
                        new
                        {
                            Id = new Guid("98479667-cd5b-4953-a442-de348acda994"),
                            IsDeleted = false,
                            MapId = new Guid("04493112-8b84-43be-b926-5a32c5524ac2"),
                            OrderNumber = 5,
                            Title = "Hydration and Electrolytes",
                            XP = 100
                        },
                        new
                        {
                            Id = new Guid("77c74f8c-a3ef-4cb8-8a2c-b71ca6ecd33e"),
                            IsDeleted = false,
                            MapId = new Guid("04493112-8b84-43be-b926-5a32c5524ac2"),
                            OrderNumber = 3,
                            Title = "Protein Quality and Timing",
                            XP = 100
                        },
                        new
                        {
                            Id = new Guid("0491fb6d-5264-4beb-88e6-a247489c4825"),
                            IsDeleted = false,
                            MapId = new Guid("04493112-8b84-43be-b926-5a32c5524ac2"),
                            OrderNumber = 4,
                            Title = "Micronutrients",
                            XP = 100
                        },
                        new
                        {
                            Id = new Guid("b1adc18d-8c55-4a74-8bf6-a9a2943fd9e7"),
                            IsDeleted = false,
                            MapId = new Guid("1afe12ea-606d-49d0-adb9-5f8311d86618"),
                            OrderNumber = 1,
                            Title = "Benefits of Resistance Training",
                            XP = 100
                        },
                        new
                        {
                            Id = new Guid("cde73646-a8fb-4131-9308-8269ea662c54"),
                            IsDeleted = false,
                            MapId = new Guid("1afe12ea-606d-49d0-adb9-5f8311d86618"),
                            OrderNumber = 2,
                            Title = "Exercises and Muscles Targeted",
                            XP = 100
                        },
                        new
                        {
                            Id = new Guid("8e10a739-c7a9-4c9e-887c-b2599be94f3a"),
                            IsDeleted = false,
                            MapId = new Guid("1afe12ea-606d-49d0-adb9-5f8311d86618"),
                            OrderNumber = 3,
                            Title = "Training Splits and Frequency",
                            XP = 100
                        },
                        new
                        {
                            Id = new Guid("81476c31-4e91-41d5-b37e-422e97b5882e"),
                            IsDeleted = false,
                            MapId = new Guid("1afe12ea-606d-49d0-adb9-5f8311d86618"),
                            OrderNumber = 4,
                            Title = "Compound vs Isolation Movements",
                            XP = 100
                        },
                        new
                        {
                            Id = new Guid("7e065ddc-a469-4bbe-b205-113c3d96f4c5"),
                            IsDeleted = false,
                            MapId = new Guid("1afe12ea-606d-49d0-adb9-5f8311d86618"),
                            OrderNumber = 5,
                            Title = "Recovery and Rest",
                            XP = 100
                        });
                });

            modelBuilder.Entity("FitFox.Data.Models.Level", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasComment("The identifier of the level.");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("LevelNumber")
                        .HasColumnType("int")
                        .HasComment("The number representing the level. Incrementing by 1.");

                    b.Property<string>("LevelTitle")
                        .HasColumnType("nvarchar(max)")
                        .HasComment("The title granted for the level. Every 10 levels the user gets title of the level.");

                    b.Property<int>("RequiredXP")
                        .HasColumnType("int")
                        .HasComment("The XP that is required to get to this level.");

                    b.HasKey("Id");

                    b.ToTable("Levels");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            IsDeleted = false,
                            LevelNumber = 1,
                            LevelTitle = "Newbie",
                            RequiredXP = 0
                        });
                });

            modelBuilder.Entity("FitFox.Data.Models.Map", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasComment("The identifier of the map.");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasComment("The description of the map.");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("MapCategory")
                        .HasColumnType("int")
                        .HasComment("The category of the map - training, nutrition, hydration, recovery, etc.");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasComment("The display name of the map.");

                    b.HasKey("Id");

                    b.ToTable("Maps");

                    b.HasData(
                        new
                        {
                            Id = new Guid("1afe12ea-606d-49d0-adb9-5f8311d86618"),
                            Description = "The basics of training with weights.",
                            IsDeleted = false,
                            MapCategory = 0,
                            Title = "Training"
                        },
                        new
                        {
                            Id = new Guid("04493112-8b84-43be-b926-5a32c5524ac2"),
                            Description = "The basics of nutrition focused on gym progression.",
                            IsDeleted = false,
                            MapCategory = 1,
                            Title = "Nutrition"
                        });
                });

            modelBuilder.Entity("FitFox.Data.Models.MappingModels.UserAchievement", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AchievementId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("EarnedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("UserId", "AchievementId");

                    b.HasIndex("AchievementId");

                    b.ToTable("UsersAchievements");
                });

            modelBuilder.Entity("FitFox.Data.Models.MappingModels.UserLesson", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("LessonId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId", "LessonId");

                    b.HasIndex("LessonId");

                    b.ToTable("UsersLessons");
                });

            modelBuilder.Entity("FitFox.Data.Models.MappingModels.UserMap", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("MapId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId", "MapId");

                    b.HasIndex("MapId");

                    b.ToTable("UsersMaps");
                });

            modelBuilder.Entity("FitFox.Data.Models.Question", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Identifier of the question.");

                    b.Property<Guid?>("CorrectAnswerId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("The identifier of the correct answer.");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid>("LessonId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Identifier of the lesson that this question belongs to.");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasComment("The question content.");

                    b.HasKey("Id");

                    b.HasIndex("CorrectAnswerId");

                    b.HasIndex("LessonId");

                    b.ToTable("Questions");

                    b.HasData(
                        new
                        {
                            Id = new Guid("65e73cd9-dec1-4e46-8342-69b204c6b226"),
                            CorrectAnswerId = new Guid("995bd8c0-98e5-441b-96f2-046c4e732022"),
                            IsDeleted = false,
                            LessonId = new Guid("26a98b9c-2a98-4714-8d28-99f6ed419834"),
                            Text = "Which are the 3 macronutrients?"
                        },
                        new
                        {
                            Id = new Guid("a8d6e1f2-5c33-4a0b-8cde-7e2f1a9b3d45"),
                            CorrectAnswerId = new Guid("ad15d6de-bc27-4f9c-925f-6efe5023521b"),
                            IsDeleted = false,
                            LessonId = new Guid("26a98b9c-2a98-4714-8d28-99f6ed419834"),
                            Text = "Which macronutrient regulates hormone production?"
                        },
                        new
                        {
                            Id = new Guid("c1f2b3e4-7d8a-4e5b-b2c3-9f0a1d2e3b56"),
                            CorrectAnswerId = new Guid("971018fd-870c-4834-b53e-9db728272f58"),
                            IsDeleted = false,
                            LessonId = new Guid("26a98b9c-2a98-4714-8d28-99f6ed419834"),
                            Text = "Which macronutrient is the main source of energy for the body?"
                        },
                        new
                        {
                            Id = new Guid("d4e5f6a7-8b9c-4d0e-9f1a-2b3c4d5e6f78"),
                            CorrectAnswerId = new Guid("cd72868e-1d3c-40e2-99d2-9be1c6482f07"),
                            IsDeleted = false,
                            LessonId = new Guid("26a98b9c-2a98-4714-8d28-99f6ed419834"),
                            Text = "Which nutrient is primarily used for muscle repair?"
                        },
                        new
                        {
                            Id = new Guid("83fc33fc-0db2-4695-a950-c494eb58a73c"),
                            CorrectAnswerId = new Guid("5b2e033a-3b69-42df-9b10-ac04fefbc4bd"),
                            IsDeleted = false,
                            LessonId = new Guid("26a98b9c-2a98-4714-8d28-99f6ed419834"),
                            Text = "How many calories does 1 gram of fat contain?"
                        },
                        new
                        {
                            Id = new Guid("e58fca52-c2da-44a4-b62f-9bd9bd7bb583"),
                            CorrectAnswerId = new Guid("e00f1bae-9e02-4afb-871f-23a1a3a9884f"),
                            IsDeleted = false,
                            LessonId = new Guid("26a98b9c-2a98-4714-8d28-99f6ed419834"),
                            Text = "How many calories does 1 gram of carbohydrates contain?"
                        },
                        new
                        {
                            Id = new Guid("c46cf154-ee4c-4c5d-ac35-4b4cf69639ce"),
                            CorrectAnswerId = new Guid("fe9167a4-2f11-4875-899d-83c9d4b031b7"),
                            IsDeleted = false,
                            LessonId = new Guid("26a98b9c-2a98-4714-8d28-99f6ed419834"),
                            Text = "How many calories does 1 gram of protein contain?"
                        },
                        new
                        {
                            Id = new Guid("725ac1b4-5362-484a-964a-4a1bc95a2aab"),
                            IsDeleted = false,
                            LessonId = new Guid("97300d33-6cc5-48ba-b495-ff21d5b16419"),
                            Text = "What is the typical protein intake per kg of body weight for a person trying to build muscle?"
                        },
                        new
                        {
                            Id = new Guid("ab0fda0c-dca4-4b12-a690-8e1b311ee5de"),
                            IsDeleted = false,
                            LessonId = new Guid("97300d33-6cc5-48ba-b495-ff21d5b16419"),
                            Text = "For a cutting diet, which macronutrient is often reduced first?"
                        },
                        new
                        {
                            Id = new Guid("c3dc5b10-c49e-4c55-82bf-19588f1ce0a4"),
                            IsDeleted = false,
                            LessonId = new Guid("97300d33-6cc5-48ba-b495-ff21d5b16419"),
                            Text = "Which macronutrient is usually prioritized for muscle gain?"
                        },
                        new
                        {
                            Id = new Guid("b4baf54c-59b6-4b9d-91d9-7e3352b5d3ee"),
                            IsDeleted = false,
                            LessonId = new Guid("97300d33-6cc5-48ba-b495-ff21d5b16419"),
                            Text = "For someone on a low-carb diet, which macronutrient is usually increased to compensate for reduced carbs?"
                        },
                        new
                        {
                            Id = new Guid("c29ae0bc-eb61-45c1-be09-2e24ca66862b"),
                            IsDeleted = false,
                            LessonId = new Guid("98479667-cd5b-4953-a442-de348acda994"),
                            Text = "What is the main function of water in the body?"
                        },
                        new
                        {
                            Id = new Guid("d76f8572-c76d-4ea6-96e2-88f94b2ef5db"),
                            IsDeleted = false,
                            LessonId = new Guid("98479667-cd5b-4953-a442-de348acda994"),
                            Text = "Which electrolyte is most important for muscle contraction and nerve function?"
                        },
                        new
                        {
                            Id = new Guid("5ef2fcf6-df7a-4f3d-9958-3d3c20fe9b90"),
                            IsDeleted = false,
                            LessonId = new Guid("98479667-cd5b-4953-a442-de348acda994"),
                            Text = "Which electrolyte helps regulate heart rhythm and fluid balance?"
                        },
                        new
                        {
                            Id = new Guid("4c550c86-a27f-480d-8a34-26a5d94d7bb3"),
                            IsDeleted = false,
                            LessonId = new Guid("98479667-cd5b-4953-a442-de348acda994"),
                            Text = "A common sign of dehydration is:"
                        },
                        new
                        {
                            Id = new Guid("3b1a72e5-e73e-4e8d-833e-b92a61eb2664"),
                            IsDeleted = false,
                            LessonId = new Guid("98479667-cd5b-4953-a442-de348acda994"),
                            Text = "How many liters of water are generally recommended per day for an average adult?"
                        },
                        new
                        {
                            Id = new Guid("2cd2b95d-63c0-4c7f-9485-3df385a91476"),
                            IsDeleted = false,
                            LessonId = new Guid("98479667-cd5b-4953-a442-de348acda994"),
                            Text = "Which electrolyte is often lost in large amounts through sweat?"
                        },
                        new
                        {
                            Id = new Guid("3bbce0fb-8e12-4a03-837d-9ac269f282ff"),
                            IsDeleted = false,
                            LessonId = new Guid("98479667-cd5b-4953-a442-de348acda994"),
                            Text = "Magnesium helps with all of the following EXCEPT:"
                        },
                        new
                        {
                            Id = new Guid("e74d6670-97b6-42c9-8464-881dbb6bfa9d"),
                            IsDeleted = false,
                            LessonId = new Guid("77c74f8c-a3ef-4cb8-8a2c-b71ca6ecd33e"),
                            Text = "Which protein source is considered “complete”, containing all essential amino acids?"
                        },
                        new
                        {
                            Id = new Guid("b850b9da-babb-465e-96b4-99639f04711e"),
                            IsDeleted = false,
                            LessonId = new Guid("77c74f8c-a3ef-4cb8-8a2c-b71ca6ecd33e"),
                            Text = "When is protein consumption most effective for muscle recovery?"
                        },
                        new
                        {
                            Id = new Guid("34c91eb1-1e3b-4f7b-bf02-8b9f34653023"),
                            IsDeleted = false,
                            LessonId = new Guid("77c74f8c-a3ef-4cb8-8a2c-b71ca6ecd33e"),
                            Text = "Which protein source is faster digesting and ideal post-workout?"
                        },
                        new
                        {
                            Id = new Guid("cb1eb27c-eb7a-49f1-bf83-5b89a8dca794"),
                            IsDeleted = false,
                            LessonId = new Guid("77c74f8c-a3ef-4cb8-8a2c-b71ca6ecd33e"),
                            Text = "Casein protein is best consumed:"
                        },
                        new
                        {
                            Id = new Guid("ddbf95d6-d691-48e2-8c7d-6ce2150e3ac5"),
                            IsDeleted = false,
                            LessonId = new Guid("77c74f8c-a3ef-4cb8-8a2c-b71ca6ecd33e"),
                            Text = "Combining different plant proteins can help:"
                        },
                        new
                        {
                            Id = new Guid("0ef6cf36-8764-4924-9b01-5fcc247c96aa"),
                            IsDeleted = false,
                            LessonId = new Guid("0491fb6d-5264-4beb-88e6-a247489c4825"),
                            Text = "Which of the following are considered micronutrients?"
                        },
                        new
                        {
                            Id = new Guid("4fbd5ee9-c603-4530-a325-0b8c94d87e52"),
                            IsDeleted = false,
                            LessonId = new Guid("0491fb6d-5264-4beb-88e6-a247489c4825"),
                            Text = "Which vitamin is essential for calcium absorption and bone health?"
                        },
                        new
                        {
                            Id = new Guid("fc987683-272e-4874-9ec0-adbd1d4d43f0"),
                            IsDeleted = false,
                            LessonId = new Guid("0491fb6d-5264-4beb-88e6-a247489c4825"),
                            Text = "Which mineral is important for oxygen transport in the blood?"
                        },
                        new
                        {
                            Id = new Guid("1020c72c-9f20-4b04-8523-e2a9dc643ed2"),
                            IsDeleted = false,
                            LessonId = new Guid("0491fb6d-5264-4beb-88e6-a247489c4825"),
                            Text = "A deficiency in Vitamin C can lead to which condition?"
                        },
                        new
                        {
                            Id = new Guid("af7f8faf-0b47-43a7-bce0-2120af75c39c"),
                            IsDeleted = false,
                            LessonId = new Guid("0491fb6d-5264-4beb-88e6-a247489c4825"),
                            Text = "Which group of vitamins is fat-soluble?"
                        },
                        new
                        {
                            Id = new Guid("6aea4f8b-3785-4027-8532-6592c9436898"),
                            IsDeleted = false,
                            LessonId = new Guid("0491fb6d-5264-4beb-88e6-a247489c4825"),
                            Text = "Zinc plays an important role in:"
                        },
                        new
                        {
                            Id = new Guid("99e612f3-3e52-4616-8ea1-19d620463779"),
                            IsDeleted = false,
                            LessonId = new Guid("0491fb6d-5264-4beb-88e6-a247489c4825"),
                            Text = "Which vitamin is primarily produced by the body when exposed to sunlight?"
                        },
                        new
                        {
                            Id = new Guid("3da3629a-ace4-45f2-900b-6c134ba6231b"),
                            IsDeleted = false,
                            LessonId = new Guid("b1adc18d-8c55-4a74-8bf6-a9a2943fd9e7"),
                            Text = "What is one of the main benefits of resistance training?"
                        },
                        new
                        {
                            Id = new Guid("0b831d70-b6e1-4eb6-8c5a-ac03c7d5d62f"),
                            IsDeleted = false,
                            LessonId = new Guid("b1adc18d-8c55-4a74-8bf6-a9a2943fd9e7"),
                            Text = "Resistance training can help prevent which age-related condition?"
                        },
                        new
                        {
                            Id = new Guid("cbb7907f-d0ab-4b6a-90e2-99312cdf12e4"),
                            IsDeleted = false,
                            LessonId = new Guid("b1adc18d-8c55-4a74-8bf6-a9a2943fd9e7"),
                            Text = "How does resistance training affect metabolism?"
                        },
                        new
                        {
                            Id = new Guid("4420dd55-0f57-439b-bc4b-47623fe05e5c"),
                            IsDeleted = false,
                            LessonId = new Guid("b1adc18d-8c55-4a74-8bf6-a9a2943fd9e7"),
                            Text = "Resistance training can help with fat loss primarily by:"
                        },
                        new
                        {
                            Id = new Guid("196f6df9-6234-499b-9309-c6b0cd29e349"),
                            IsDeleted = false,
                            LessonId = new Guid("b1adc18d-8c55-4a74-8bf6-a9a2943fd9e7"),
                            Text = "Which of the following is a mental health benefit of resistance training?"
                        },
                        new
                        {
                            Id = new Guid("734b09f7-245b-43cf-bf1a-87a2ead54981"),
                            IsDeleted = false,
                            LessonId = new Guid("b1adc18d-8c55-4a74-8bf6-a9a2943fd9e7"),
                            Text = "Resistance training improves bone health by:"
                        },
                        new
                        {
                            Id = new Guid("706cec35-8678-40a3-bf08-3f4a001765e5"),
                            IsDeleted = false,
                            LessonId = new Guid("b1adc18d-8c55-4a74-8bf6-a9a2943fd9e7"),
                            Text = "Long-term resistance training can reduce the risk of:"
                        },
                        new
                        {
                            Id = new Guid("8d2dbe17-1c9e-45f7-8fd2-d38f4d7f43ff"),
                            IsDeleted = false,
                            LessonId = new Guid("cde73646-a8fb-4131-9308-8269ea662c54"),
                            Text = "Which primary muscle does the bench press target?"
                        },
                        new
                        {
                            Id = new Guid("f68f4855-4f08-4e5e-9480-497f2e7f70c5"),
                            IsDeleted = false,
                            LessonId = new Guid("cde73646-a8fb-4131-9308-8269ea662c54"),
                            Text = "The squat primarily works which muscle group?"
                        },
                        new
                        {
                            Id = new Guid("da4b1734-79df-4b91-a69f-7c52b4b7553a"),
                            IsDeleted = false,
                            LessonId = new Guid("cde73646-a8fb-4131-9308-8269ea662c54"),
                            Text = "Deadlifts primarily target:"
                        },
                        new
                        {
                            Id = new Guid("b6d72991-5934-4d11-8c64-2144493e4fc6"),
                            IsDeleted = false,
                            LessonId = new Guid("cde73646-a8fb-4131-9308-8269ea662c54"),
                            Text = "Pull-ups primarily strengthen which muscle group?"
                        },
                        new
                        {
                            Id = new Guid("bc00cf25-bf28-4994-92ea-34b3c1cf2b8e"),
                            IsDeleted = false,
                            LessonId = new Guid("cde73646-a8fb-4131-9308-8269ea662c54"),
                            Text = "Which exercise is best for isolating the biceps?"
                        },
                        new
                        {
                            Id = new Guid("8b071bdd-25b1-4ab2-9c64-32e44e2eb889"),
                            IsDeleted = false,
                            LessonId = new Guid("cde73646-a8fb-4131-9308-8269ea662c54"),
                            Text = "Which muscle is primarily targeted by the overhead shoulder press?"
                        },
                        new
                        {
                            Id = new Guid("b77e9f69-16dc-4192-9c86-cfa9ccf86a5b"),
                            IsDeleted = false,
                            LessonId = new Guid("cde73646-a8fb-4131-9308-8269ea662c54"),
                            Text = "Lunges are most effective for strengthening:"
                        },
                        new
                        {
                            Id = new Guid("dce5b4e5-c46d-4b34-b5ae-14e67d6b753e"),
                            IsDeleted = false,
                            LessonId = new Guid("8e10a739-c7a9-4c9e-887c-b2599be94f3a"),
                            Text = "What is a “training split” in fitness?"
                        },
                        new
                        {
                            Id = new Guid("39d43280-d51f-4a8e-921f-97b6f4b2873e"),
                            IsDeleted = false,
                            LessonId = new Guid("8e10a739-c7a9-4c9e-887c-b2599be94f3a"),
                            Text = "Which is a common beginner-friendly training split?"
                        },
                        new
                        {
                            Id = new Guid("e70a94b3-2a6d-4f7b-8250-9f43c5ac4c72"),
                            IsDeleted = false,
                            LessonId = new Guid("8e10a739-c7a9-4c9e-887c-b2599be94f3a"),
                            Text = "How many times per week should a beginner ideally train each muscle group?"
                        },
                        new
                        {
                            Id = new Guid("7a37747e-9f9c-4d6d-a25a-10ee17d64a09"),
                            IsDeleted = false,
                            LessonId = new Guid("8e10a739-c7a9-4c9e-887c-b2599be94f3a"),
                            Text = "What is the main advantage of a full-body workout split?"
                        },
                        new
                        {
                            Id = new Guid("57b4cf97-88e2-4b77-a66a-dfa5704aa3cb"),
                            IsDeleted = false,
                            LessonId = new Guid("8e10a739-c7a9-4c9e-887c-b2599be94f3a"),
                            Text = "Which training split is best for maximizing recovery while still training frequently?"
                        },
                        new
                        {
                            Id = new Guid("f35e77c4-447c-46f3-893e-62110c2ff969"),
                            IsDeleted = false,
                            LessonId = new Guid("8e10a739-c7a9-4c9e-887c-b2599be94f3a"),
                            Text = "Why is rest important between training sessions for the same muscle group?"
                        },
                        new
                        {
                            Id = new Guid("3d1a7d0b-029c-41f3-81fd-cb53ff5ed0ea"),
                            IsDeleted = false,
                            LessonId = new Guid("8e10a739-c7a9-4c9e-887c-b2599be94f3a"),
                            Text = "An advanced lifter looking to focus on lagging muscle groups might benefit most from:"
                        },
                        new
                        {
                            Id = new Guid("04ecf251-b526-4445-a6f6-a6c7dfdd586a"),
                            IsDeleted = false,
                            LessonId = new Guid("81476c31-4e91-41d5-b37e-422e97b5882e"),
                            Text = "What is a compound movement?"
                        },
                        new
                        {
                            Id = new Guid("ed946370-816b-4175-bfee-cc24d3d3c971"),
                            IsDeleted = false,
                            LessonId = new Guid("81476c31-4e91-41d5-b37e-422e97b5882e"),
                            Text = "Which of the following is an example of a compound movement?"
                        },
                        new
                        {
                            Id = new Guid("562c6f2d-4216-4f46-b74b-a764a7ad5418"),
                            IsDeleted = false,
                            LessonId = new Guid("81476c31-4e91-41d5-b37e-422e97b5882e"),
                            Text = "Which of the following is an isolation exercise?"
                        },
                        new
                        {
                            Id = new Guid("a9fced86-bd78-4901-b983-f05a2ad96bcd"),
                            IsDeleted = false,
                            LessonId = new Guid("81476c31-4e91-41d5-b37e-422e97b5882e"),
                            Text = "What is the main benefit of compound movements?"
                        },
                        new
                        {
                            Id = new Guid("1e3c972d-3549-4d00-8ca5-88ac510abe63"),
                            IsDeleted = false,
                            LessonId = new Guid("81476c31-4e91-41d5-b37e-422e97b5882e"),
                            Text = "Why are isolation exercises useful?"
                        },
                        new
                        {
                            Id = new Guid("2ca88517-a1ad-4bc9-9283-0e4100d60dcd"),
                            IsDeleted = false,
                            LessonId = new Guid("81476c31-4e91-41d5-b37e-422e97b5882e"),
                            Text = "Which is the best approach for building a balanced physique?"
                        },
                        new
                        {
                            Id = new Guid("905e3202-c416-470b-8e11-ce66a9f7a534"),
                            IsDeleted = false,
                            LessonId = new Guid("81476c31-4e91-41d5-b37e-422e97b5882e"),
                            Text = "Why are compound lifts often performed at the beginning of a workout?"
                        },
                        new
                        {
                            Id = new Guid("018a8f7d-e12b-49d5-8718-889aa668cafb"),
                            IsDeleted = false,
                            LessonId = new Guid("7e065ddc-a469-4bbe-b205-113c3d96f4c5"),
                            Text = "Why is recovery important after training?"
                        },
                        new
                        {
                            Id = new Guid("d3207231-b15e-428f-b6e7-ab53471202af"),
                            IsDeleted = false,
                            LessonId = new Guid("7e065ddc-a469-4bbe-b205-113c3d96f4c5"),
                            Text = "Which of the following is a type of active recovery?"
                        },
                        new
                        {
                            Id = new Guid("6632e20e-4ff2-4342-8af2-698acaf6e495"),
                            IsDeleted = false,
                            LessonId = new Guid("7e065ddc-a469-4bbe-b205-113c3d96f4c5"),
                            Text = "How many hours of sleep are generally recommended for optimal recovery?"
                        },
                        new
                        {
                            Id = new Guid("5f83b77f-09eb-43ab-aac6-1ba1a74a8225"),
                            IsDeleted = false,
                            LessonId = new Guid("7e065ddc-a469-4bbe-b205-113c3d96f4c5"),
                            Text = "What is a deload week?"
                        },
                        new
                        {
                            Id = new Guid("6c611141-34e9-4ae5-892c-27106d39782d"),
                            IsDeleted = false,
                            LessonId = new Guid("7e065ddc-a469-4bbe-b205-113c3d96f4c5"),
                            Text = "Which nutrient is particularly important for muscle repair?"
                        },
                        new
                        {
                            Id = new Guid("6d2a72e4-ce9c-4f3b-a2ba-48667f8d6062"),
                            IsDeleted = false,
                            LessonId = new Guid("7e065ddc-a469-4bbe-b205-113c3d96f4c5"),
                            Text = "Which of the following can negatively affect recovery?"
                        },
                        new
                        {
                            Id = new Guid("27365168-3b26-4638-927a-0a0d32108cd7"),
                            IsDeleted = false,
                            LessonId = new Guid("7e065ddc-a469-4bbe-b205-113c3d96f4c5"),
                            Text = "Which strategy helps reduce delayed onset muscle soreness (DOMS)?"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("FitFox.Data.Models.Answer", b =>
                {
                    b.HasOne("FitFox.Data.Models.Question", "Question")
                        .WithMany("AnswerOptions")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Question");
                });

            modelBuilder.Entity("FitFox.Data.Models.ApplicationUser", b =>
                {
                    b.HasOne("FitFox.Data.Models.Level", "Level")
                        .WithMany("Users")
                        .HasForeignKey("LevelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Level");
                });

            modelBuilder.Entity("FitFox.Data.Models.Lesson", b =>
                {
                    b.HasOne("FitFox.Data.Models.Map", "Map")
                        .WithMany("Lessons")
                        .HasForeignKey("MapId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Map");
                });

            modelBuilder.Entity("FitFox.Data.Models.MappingModels.UserAchievement", b =>
                {
                    b.HasOne("FitFox.Data.Models.Achievement", "Achievement")
                        .WithMany("AchievementUsers")
                        .HasForeignKey("AchievementId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FitFox.Data.Models.ApplicationUser", "User")
                        .WithMany("UserAchievements")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Achievement");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FitFox.Data.Models.MappingModels.UserLesson", b =>
                {
                    b.HasOne("FitFox.Data.Models.Lesson", "Lesson")
                        .WithMany("LessonUsers")
                        .HasForeignKey("LessonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FitFox.Data.Models.ApplicationUser", "User")
                        .WithMany("UserLessons")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lesson");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FitFox.Data.Models.MappingModels.UserMap", b =>
                {
                    b.HasOne("FitFox.Data.Models.Map", "Map")
                        .WithMany("MapUsers")
                        .HasForeignKey("MapId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FitFox.Data.Models.ApplicationUser", "User")
                        .WithMany("UserMaps")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Map");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FitFox.Data.Models.Question", b =>
                {
                    b.HasOne("FitFox.Data.Models.Answer", "CorrectAnswer")
                        .WithMany()
                        .HasForeignKey("CorrectAnswerId");

                    b.HasOne("FitFox.Data.Models.Lesson", "Lesson")
                        .WithMany("Questions")
                        .HasForeignKey("LessonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CorrectAnswer");

                    b.Navigation("Lesson");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("FitFox.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("FitFox.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FitFox.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("FitFox.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FitFox.Data.Models.Achievement", b =>
                {
                    b.Navigation("AchievementUsers");
                });

            modelBuilder.Entity("FitFox.Data.Models.ApplicationUser", b =>
                {
                    b.Navigation("UserAchievements");

                    b.Navigation("UserLessons");

                    b.Navigation("UserMaps");
                });

            modelBuilder.Entity("FitFox.Data.Models.Lesson", b =>
                {
                    b.Navigation("LessonUsers");

                    b.Navigation("Questions");
                });

            modelBuilder.Entity("FitFox.Data.Models.Level", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("FitFox.Data.Models.Map", b =>
                {
                    b.Navigation("Lessons");

                    b.Navigation("MapUsers");
                });

            modelBuilder.Entity("FitFox.Data.Models.Question", b =>
                {
                    b.Navigation("AnswerOptions");
                });
#pragma warning restore 612, 618
        }
    }
}
